baseURL = "https://angelife.github.io/"
languageCode = "zh-cn"
title = "Angelife Notes"
theme = "PaperMod"

enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 120

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  DateFormat = "2006-01-02"

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "旧站"
  url = "/old-site/"
  weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/posts/:slug/"
