"""CSS Patch Preview — generates site_audit_patch.md (preview only)."""

from pathlib import Path
from typing import List, Optional
from . import Patch


def generate_markdown_preview(patches: List[Patch], output_path: str,
                               simulation_results: Optional[List[dict]] = None) -> str:
    """Generate a markdown patch preview file. Returns the path."""
    lines = [
        "# CSS Patch Preview",
        "",
        "**⚠️  This is preview only. No files modified.**",
        "",
        "---",
        "",
    ]

    for patch in patches:
        lines.extend(_render_patch(patch))

    if simulation_results:
        lines.append("## Impact Simulation\n")
        for sim in simulation_results:
            lines.extend(_render_simulation(sim))

    lines.append("---\n")
    lines.append("_End of preview. Generated by site-audit._\n")

    text = "\n".join(lines)
    Path(output_path).write_text(text, encoding="utf-8")
    return output_path


def _render_patch(patch: Patch) -> list:
    risk_badge = {
        "low": "✅ Low Risk",
        "medium": "⚠️ Medium Risk",
        "high": "🚫 High Risk",
    }.get(patch.risk, patch.risk)

    ptype_label = "CSS Variable" if patch.patch_type == "variable" else "Direct Color Value"

    lines = [
        f"## Token: `{patch.variable}`",
        "",
        f"**File:** `{patch.source_file}`  |  **Line:** {patch.line}",
        "",
        f"**Type:** {ptype_label}  |  **Risk:** {risk_badge}",
        "",
        "### Before",
        "",
        f"```css\n{patch.variable}: {patch.old_value};\n```",
        "",
        "### After",
        "",
        f"```css\n{patch.variable}: {patch.new_value};\n```",
        "",
        "### Reason",
        "",
        "WCAG AA contrast improvement\n",
        "### Affected Selectors",
        "",
    ]
    for sel in patch.selectors:
        lines.append(f"* `{sel}`")
    lines.append("")
    lines.append(f"**Impact:** {patch.issue_count} issue(s) affected\n")
    lines.append("---\n")
    return lines


def _render_simulation(sim: dict) -> list:
    lines = [
        f"### {sim.get('variable', 'Token')}",
        "",
        "| Metric | Before | After |",
        "|--------|--------|-------|",
        f"| Color | {sim.get('before_color', '?')} | {sim.get('after_color', '?')} |",
        f"| WCAG Ratio | {sim.get('before_ratio', '?'):.2f}:1 | {sim.get('after_ratio', '?'):.2f}:1 |",
        f"| Failed Issues | {sim.get('before_failures', '?')} | {sim.get('after_failures', '?')} |",
        "",
    ]
    return lines