#!/usr/bin/env python3
"""Post-Hugo-build script: extend index.json + generate Kindle old-site list.
Usage: python3 extend-search-index.py [hugo-site/public/ path]
Defaults to ./hugo-site/public/ relative to CWD."""
import os, glob, json, re, sys
from html import escape

PUBLIC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.getcwd(), "hugo-site", "public")
STATIC_OLD = os.path.join(os.getcwd(), "hugo-site", "static", "old-site")
PUBLIC_OLD = os.path.join(PUBLIC, "old-site")
INDEX_PATH = os.path.join(PUBLIC, "index.json")
KINDLE_PARTIAL = os.path.join(os.getcwd(), "hugo-site", "layouts", "partials", "kindle-old-site-list.html")

# ── 1. Generate Kindle old-site list partial (from static/ source) ──
os.makedirs(os.path.dirname(KINDLE_PARTIAL), exist_ok=True)

old_pages = []
for html_path in sorted(glob.glob(os.path.join(STATIC_OLD, "*.html"), recursive=False)):
    base = os.path.basename(html_path)
    if base in ("_layouts", "_site", "_posts") or base.startswith("google"):
        continue
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'<title>(.*?)</title>', content, re.DOTALL)
    title = m.group(1).strip() if m else base
    url = "/old-site/" + base
    mtime = os.path.getmtime(html_path)
    old_pages.append((mtime, title, url))

old_pages.sort(key=lambda x: x[0], reverse=True)
old_pages = old_pages[:80]

lines = ['<!-- auto-generated by extend-search-index.py -->']
lines.append('<p class="kindle-old-site-intro">旧站存档内容（80 篇），按更新时间倒序。</p>')
for _, title, url in old_pages:
    safe = escape(title)
    lines.append('    <article class="kindle-entry">')
    lines.append('      <h2><a href="{}">{}</a></h2>'.format(url, safe))
    lines.append('      <div class="kindle-entry-meta"><span>旧站存档</span></div>')
    lines.append('      <a class="kindle-read-link" href="{}">阅读 &rarr;</a>'.format(url))
    lines.append('    </article>')

with open(KINDLE_PARTIAL, "w", encoding="utf-8") as f:
    f.write('\n'.join(lines) + '\n')

print("Kindle partial: {} entries -> {}".format(len(old_pages), KINDLE_PARTIAL))

# ── 2. Extend index.json (from build output) ──
if not os.path.exists(PUBLIC_OLD):
    print("Skipping index extend: {} not found (pre-build mode)".format(PUBLIC_OLD))
    sys.exit(0)

with open(INDEX_PATH, "r", encoding="utf-8") as f:
    index = json.load(f)

existing_urls = {e.get("permalink", "") for e in index}
added = 0

for html_path in sorted(glob.glob(os.path.join(PUBLIC_OLD, "**", "*.html"), recursive=True)):
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'<title>(.*?)</title>', content, re.DOTALL)
    title = m.group(1).strip() if m else os.path.basename(html_path)
    rel_path = os.path.relpath(html_path, PUBLIC)
    permalink = "https://angelife.github.io/" + rel_path
    if permalink in existing_urls:
        continue
    summary = ""
    body_m = re.search(r'<body[^>]*>(.*?)</body>', content, re.DOTALL)
    if body_m:
        text = re.sub(r'<[^>]+>', '', body_m.group(1))
        text = re.sub(r'\s+', ' ', text).strip()
        summary = text[:200] if text else ""
    index.append({
        "categories": "旧站存档", "content": "",
        "description": summary[:160] if summary else "旧站存档文章",
        "permalink": permalink, "summary": summary,
        "tags": "旧站,存档", "title": title
    })
    existing_urls.add(permalink)
    added += 1

with open(INDEX_PATH, "w", encoding="utf-8") as f:
    json.dump(index, f, ensure_ascii=False)

print("Index extend: {} old-site entries added (total {})".format(added, len(index)))
